name: Daily Flight Scraper

on:
  schedule:
    - cron: "0 2 * * *"           # kasdien 02:00 UTC
  workflow_dispatch:              # leidžia paleisti rankiniu būdu

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scraper/flights.py

      # 👉 naujas žingsnis – prisegame ekrano nuotrauką (jei tokia yra)
      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flight-screenshot
          path: scraper/screenshot.png    # kelias tas pats kaip SS_PATH
          if-no-files-found: error        # norim klaidos, jei png neatsirado

      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily flight data update"
          add: "data/flights.csv"
