name: Daily Flight Scraper

on:
  schedule:
    - cron: "0 2 * * *"        # kasdien 02:00 UTC
  workflow_dispatch:           # mygtukas „Run workflow“

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # kad galėtų „commitinti“ CSV
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scraper/flights.py

      - name: Upload screenshot
        if: always()           # bandome visada
        uses: actions/upload-artifact@v4
        with:
          name: flight-screenshot
          path: scraper/screenshot.png
          if-no-files-found: ignore

      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily flight data update"
          add: "data/flights.csv"
